---
# AWSTemplateFormatVersion: "2018-30-05"

Description: >
  Template to launch VPC Infrastructure


Parameters:
  DnsSupport:
    Description: "Enable DNS Support"
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  DnsHostName:
    Description: "Enable DNS Host Name"
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  TenancyForInstance:
    Description:  "Select Instance Tenancy"
    Type: String
    Default: default
    AllowedValues:
      - default
      - dedicated
  VPCCidrBlock:
    Description: "Enter Cidr Block for VPC"
    Type: String
  CidrBlockForSubnetPublic:
    Description: "Cidr Ip for Subnet"
    Type: String
  CidrBlockForSubnetPrivate:
    Description: "Cidr Ip for Subnet"
    Type: String
Resources:
  MyVPC:
    Type: "AWS::EC2::VPC"
    Properties: 
      CidrBlock: !Ref VPCCidrBlock            # String
      EnableDnsSupport: !Ref DnsSupport       # Boolean
      EnableDnsHostnames: !Ref DnsHostName    # Boolean
      InstanceTenancy: !Ref TenancyForInstance
      Tags:
        - 
          Key: "Enter Key Here"
          Value: "Enter Value Here"
  MySubnetPublic:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Ref CidrBlockForSubnetPublic
      MapPublicIpOnLaunch: "true"
      VpcId: 
        Ref: MyVPC
      Tags:
        - 
          Key: "Enter Key Here"
          Value: "Enter Value Here"
  MySubnetPrivate:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Ref CidrBlockForSubnetPrivate
      MapPublicIpOnLaunch: "false"
      VpcId: 
        Ref: MyVPC
      Tags:
        - 
          Key: "Enter Key Here"
          Value: "Enter Value Here"
  MyInternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        -
          Key: "Enter Key Here"
          Value: "Enter Value Here"
