Parameters:
  DnsSupport:
    Description: "Enable DNS Support"
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  DnsHostName:
    Description: "Enable DNS Host Name"
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  TenancyForInstance:
    Description:  "Select Instance Tenancy"
    Type: String
    Default: default
    AllowedValues:
      - default
      - dedicated
  VPCCidrBlock:
    Description: "Enter Cidr Block for VPC"
    Type: String
  GenerateIpv6AddressForSubnet:
    Description: "Create Ipv6 Address for Subnet"
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  CidrBlockForSubnet:
    Description: "Cidr Ip for Subnet"
    Type: String
  Ipv6CidrForSubnet:
    Description: "Ipv6 Cidr for Subnet. {Enter only if GenerateIpv6AddressforSubnet is 'true'}"
    Type: String
  MapPublicIpForSubnet:
    Description: "Instances Launched in this subnet should have a public IP"
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
Resources:
  MyVPC:
    Type: "AWS::EC2::VPC"
    Properties: 
      CidrBlock: !Ref VPCCidrBlock            # String
      EnableDnsSupport: !Ref DnsSupport       # Boolean
      EnableDnsHostnames: !Ref DnsHostName    # Boolean
      InstanceTenancy: !Ref TenancyForInstance
      Tags:
        - 
          Key: "Enter Key Here"
          Value: "Enter Value Here"
  MySubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AssignIpv6AddressOnCreation: !Ref GenerateIpv6AddressForSubnet
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Ref CidrBlockForSubnet
      Ipv6CidrBlock: !Ref Ipv6CidrForSubnet
      MapPublicIpOnLaunch: !Ref MapPublicIpForSubnet
      VpcId: MyVPC
      Tags:
        - 
          Key: "Enter Key Here"
          Value: "Enter Value Here"