---

# This Template uses Amazon Linux AMI

Description: > 
  Write EC2 Instance Logs to CloudWatch

Parameters:
  InstanceType:
    Description: Select Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.large
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge
      - m2.xlarge
      - m2.2xlarge
      - m2.4xlarge
      - m3.xlarge
      - m3.2xlarge
      - c1.medium
      - c1.xlarge
  InstanceName:
    Description: Name of the Instance
    Type: String
  KeyName: 
    Description: Key Pair to ssh into Instance
    Type: AWS::EC2::KeyPair::KeyName
  MyVPC:
    Description: Select VPC
    Type: AWS::EC2::VPC::Id

Mappings:
  RegionMap:
    us-east-1:
      amazonLinux: "ami-14c5486b"
    us-east-2:
      amazonLinux: "ami-922914f7"
    ap-south-1:
      amazonLinux: "ami-76d6f519"
    ap-northeast-1:
      amazonLinux: "ami-92df37ed"

Resources:
  LinuxInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", amazonLinux]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - Ref: MySecurityGroupIngress
        - Ref: MySecurityGroupEgress
      UserData:
        Fn::Base64:
          Fn::Join:
          - "\n"
          - - "#!/bin/bash -v"
            - "sudo yum install awslogs -y"
            - "sudo rm -rf /etc/awslogs/awscli.conf"
            - "sudo rm -rf /etc/awslogs/awslogs.conf"
            - "sudo echo -e '[plugins]\ncwlogs = cwlogs\n[default]\nregion = ap-south-1' > /etc/awslogs/awscli.conf"
            - "sudo echo -e '[general]\nstate_file = /var/lib/awslogs/agent-state\n' > /etc/awslogs/awslogs.conf"
            - "sudo echo -e '[/var/log/cloud-init]\ndatetime_format = %b %d %H:%M:%S\nfile = /var/log/cloud-init.log\nbuffer_duration = 5000\nlog_stream_name = {instance_id}\ninitial_position = start_of_file\nlog_group_name = /var/log/cloud-init' >> /etc/awslogs/awslogs.conf"
            - "sudo service awslogs start"
  MySecurityGroupEgress:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Test Security group (Egress)"
      VpcId: !Ref MyVPC
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "443"
          ToPort: "443"
          CidrIp: 0.0.0.0/0
      Tags:
        -
          Key: "Name"
          Value: "EgressSecurity"
  MySecurityGroupIngress:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Test Security Group (Ingress)"
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "443"
          ToPort: "443"
          CidrIp: 0.0.0.0/0
      Tags:
        -
          Key: "Name"
          Value: "IngressSecurity"

