---

# This Template uses Amazon Linux AMI

Description: > Write EC2 Instance Logs to CloudWatch
Paramters:
  InstanceType:
    Description: Select Instance Type
    Type: String
    Default: t2.micro
    AllowedValue:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.large
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge
      - m2.xlarge
      - m2.2xlarge
      - m2.4xlarge
      - m3.xlarge
      - m3.2xlarge
      - c1.medium
      - c1.xlarge
  InstanceName:
    Description: Name of the Instance
    Type: String
  KeyName: 
    Description: Key Pair to ssh into Instance
    Type: AWS::EC2::Keypair::KeyName
  MyVPC:
    Description: Select VPC
    Type: AWS::EC2::VPC::Id

Mappings:
  RegionMap:
    us-east-1:
      amazonLinux: "ami-14c5486b"
    us-east-2:
      amazonLinux: "ami-922914f7"
    ap-south-1:
      amazonLinux: "ami-76d6f519"
    ap-northeast-1:
      amazonLinux: "ami-92df37ed"

Resources:
  LinuxInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", amazonLinux]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
