---
Description: > Windows Template

Parameters:
  InstanceType:
    Description: Select Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.large
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge
      - m2.xlarge
      - m2.2xlarge
      - m2.4xlarge
      - m3.xlarge
      - m3.2xlarge
      - c1.medium
      - c1.xlarge
  InstanceName:
    Description: Name of the Instance
    Type: String
  KeyName: 
    Description: Key Pair to ssh into Instance
    Type: AWS::EC2::KeyPair::KeyName
  MyVPC:
    Description: Select VPC
    Type: AWS::EC2::VPC::Id
  IamRole:
    Description: Role Name
    Type: String
    Default: cloudwatch

Mappings:
  RegionMap:
    us-east-1:
      amazonLinux: "ami-14c5486b"
      regionCode: us-east-1
    us-east-2:
      amazonLinux: "ami-922914f7"
      regionCode: us-east-2
    ap-south-1:
      amazonLinux: "ami-76d6f519"
      regionCode: ap-south-1
    ap-northeast-1:
      amazonLinux: "ami-92df37ed"
      regionCode: ap-northeast-1

Resources:
  CloudWatchInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
      - {Ref: IamRole}
  WindowsInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", amazonLinux]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref CloudWatchInstanceProfile
      SecurityGroupIds:
        - Ref: MySecurityGroupIngress
        - Ref: MySecurityGroupEgress
      UserData:
        Fn::Base64:
          Fn::Join:
          - " "
          - - "powershell.exe wget c:\cloud.zip https://s3.amazonaws.com/amazoncloudwatch-agent/windows/amd64/latest/AmazonCloudWatchAgent.zip"
            - "powershell.exe expand-archive c:\cloud.zip c:\amazonAgent"
            - "powershell.exe c:\amazonAgent\install.ps1"
            - "powershell.exe wget c:\'Program Files'\aws\amazon-cloud-watch\\config.json https://github.com/nautiyaldeepak/Cloudformation-Template/blob/master/CloudWatch/config.json"
            - "amazon-cloudwatch-agent-ctl.ps1 -a fetch-config -m ec2 -c file:'c:\\Program Files\\aws\\amazon-cloudwatch-agent\\config.json' -s"
  MySecurityGroupEgress:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Test Security group (Egress)"
      VpcId: !Ref MyVPC
      SecurityGroupEgress:
        - IpProtocol: rdp
          FromPort: "3389"
          ToPort: "3389"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "443"
          ToPort: "443"
          CidrIp: 0.0.0.0/0
      Tags:
        -
          Key: "Name"
          Value: "EgressSecurity"
  MySecurityGroupIngress:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Test Security Group (Ingress)"
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: rdp
          FromPort: "3389"
          ToPort: "3389"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "443"
          ToPort: "443"
          CidrIp: 0.0.0.0/0
      Tags:
        -
          Key: "Name"
          Value: "IngressSecurity"
