# Template to Launch RDS Instance

Description: > This template is to launch RDS Instance

Parameters:
  DatabaseInstanceClass:
    Description: "Instances Size"
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.large
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge
      - m2.xlarge
      - m2.2xlarge
      - m2.4xlarge
      - m3.xlarge
      - m3.2xlarge
      - c1.medium
      - c1.xlarge
  DiskStorage:
    Description: "Database Storage Disk"
    Type: String
    Default: 20
  AutoVersionUpgrade:
    Description: "Enable Auto Version Upgrade"
    Type: Boolean
    Default: True
    AllowedValues:
      - True
      - False
  MultiAZs:
    Description: "Enable Multi AZ Deployment"
    Type: Boolean
    Default: True
    AllowedValues:
      - True
      - False
  BackUpRetentionPeriod:
    Description: "Automated Snapshot Retention Period after Database is deleted"
    Type: String
    Default: 30
  DatabaseName:
    Description: "Name of the Database"
    Type: String
  SnapshotTags:
    Description: Copy DB Instance tags to Snapshots
    Type: Boolean
    Default: True
    AllowedValues:
      - True
      - False
    RDSParameterGroups:
      Description: "Select Parameter Group"
      Type: AWS::RDS::DBParameterGroup
    RDSSecurityGroup:
      Description: "Select Security group"
      Type: AWS::RDS::DBSecurityGroup
    SnapshotName:
      Description: "Name for Snapshots for this DB"
      Type: String


Resources:
  MyRDSInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: !Ref DiskStorage
      AllowMajorVersionUpgrade: !Ref AutoVersionUpgrade
      AllowMinorVersionUpgrade: !Ref AutoVersionUpgrade
      BackupRetentionPeriod: !Ref BackUpRetentionPeriod
      CopyTagsToSnapshot: !Ref SnapshotTags
      DBInstanceClass: !Ref DatabaseInstanceClass
      DBName: !Ref DatabaseName
      DBParameterGroupName: !Ref RDSParameterGroups
      DBSecurityGroups: !Ref RDSSecurityGroup
      DBSnapshotIdentifier: !Ref SnapshotName