---
# AWSTemplateFormatVersion: "2018-30-05"

Description: >
  Template to create EC2 Security Groups
  Ingress & Egress Security Groups


Parameters:
  MyVPC:
    Description: Select VPC
    Type: AWS::EC2::VPC::Id
Resources:
  # Creating Security Group for outgoing traffic
  MySecurityGroupEgress:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Test Security group (Egress)"
      VpcId: !Ref MyVPC   # Can also hard code the vpc Id
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "443"
          ToPort: "443"
          CidrIp: 0.0.0.0/0
      Tags:
        -
          Key: "Enter Key Value"
          Value: "Enter Value"
        -
          Key: "Enter Key Value"
          Value: "Enter Value"

  # Creating Security Group for incoming traffic
  MySecurityGroupIngress:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Test Security Group (Ingress)"
      VpcId: !Ref MyVPC    # Can also hard code the vpc Id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "443"
          ToPort: "443"
          CidrIp: 0.0.0.0/0
      Tags:
        -
          Key: "Enter Key Value"
          Value: "Enter Value"
        -
          Key: "Enter Key Value"
          Value: "Enter Value"
